### ISSUE TITLE
"--target" will always be ignored

### ISSUE THREAD

**Issue by DebuggingYou** [s14r/bitbucket-cli#3]
By creating a new pull request, I always face the issue, that the target is always the default (master) instead the one setup in the command. 

The command looks like this: 
`bitbucket-cli create-pull-request --source "Source_Branch" --target "Target_Branch" --username $uname --password $pword $slug "Foo Bar"`

Am I missing something? Thank you in advice for your help!

**Comment by s14r** [comment]
Hey,

thanks for letting me know, I’ll check it asap and will come back to you.

Have a good one

**Comment by s14r** [comment]
Sorry, was a tough time – will have a look tomorrow as I have a bit of time there.

**Comment by s14r** [comment]
Well, it's "just" been three years :D
Best excuse: I have kids now :)

Its now fixed in v0.5.5
